### ISSUE TITLE
pycoin won't import

### ISSUE THREAD

**Issue by capricornuscipher** [cdecker/pycoin#4]
I see the egg in my site packages.
And if I run pip list...
pycoin (0.1.0)
is listed but on the shell or in a script I get the follow kind of message....
>>> import pycoin
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pycoin
ImportError: No module named 'pycoin'

Any pointers on what else to check?

**Comment by cdecker** [comment]
Pycoin is the name of the library, not the name of the importable package. Try `import bitcoin`, that should work.
